# Generated by Django 6.0.4 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_course_course_topics_topic_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
