# Generated by Django 6.0.4 on 2026-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_topic_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
