# Generated by Django 6.0.4 on 2026-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_topic_generator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('problems', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('questions_per_day', models.IntegerField(default=10)),
            ],
        ),
    ]
