# Generated by Django 6.0.4 on 2026-07-18 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dailydeck_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='dailydeck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailydeck',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dailydeck',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_deck'),
        ),
        migrations.AddField(
            model_name='usertopicselection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='myapp.topic'),
        ),
        migrations.AddField(
            model_name='usertopicselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertopicselection',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic'),
        ),
    ]
