# Generated by Django 6.0.4 on 2026-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_dailypractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeck',
            name='needs_regen',
            field=models.BooleanField(default=False),
        ),
    ]
