# Generated by Django 6.0.4 on 2026-09-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_dailydeck_needs_regen'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='role_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
