# Generated by Django 6.0.4 on 2026-09-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_settings_role_settings_role_chosen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('topics', 'Topics'), ('topics_sm2', 'Topics + SM-2'), ('deck', 'Deck'), ('deck_sm2', 'Deck + SM-2')], default='topics', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck_scope', models.CharField(blank=True, choices=[('all', 'All selected'), ('course', 'Course'), ('unit', 'Unit')], max_length=10, null=True)),
                ('unit_key', models.CharField(blank=True, max_length=64, null=True)),
                ('deck_size', models.IntegerField(default=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck_assignments', to='myapp.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_code', models.CharField(max_length=12, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='myapp.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('problems', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='myapp.assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='myapp.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempts', models.IntegerField(default=1)),
                ('outcome', models.CharField(max_length=20)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts', to='myapp.topic')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myapp.studentassignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_topics', to='myapp.assignment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_topics', to='myapp.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'topic'), name='unique_assignment_topic')],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.classroom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'student'), name='unique_classroom_student')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='myapp.assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='myapp.classroom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'classroom'), name='unique_assignment_classroom')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentassignment',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='assignmentattempt',
            constraint=models.UniqueConstraint(fields=('student_assignment', 'problem_index'), name='unique_studentassignment_problem'),
        ),
    ]
