# Generated by Django 6.0.4 on 2026-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_assignment_classroom_studentassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deck_scope',
            field=models.CharField(blank=True, choices=[('all', 'All selected'), ('topics', 'Teacher-picked topics'), ('course', 'Course'), ('unit', 'Unit')], max_length=10, null=True),
        ),
    ]
