# Generated by Django 6.0.4 on 2026-09-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_proficiencysnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentattempt',
            name='unique_studentassignment_problem',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deck_scope',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='unit_key',
        ),
        migrations.RemoveField(
            model_name='assignmenttopic',
            name='num_questions',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='current_index',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='problems',
        ),
        migrations.DeleteModel(
            name='AssignmentAttempt',
        ),
    ]
