"""
Django settings for the solveki backend (config project).

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Verify TLS against the operating system's trust store instead of the CA
# bundle vendored by certifi/requests. This matters when something on the host
# intercepts HTTPS (corporate proxies, or antivirus "web shields" like Avast)
# and re-signs traffic with a locally-trusted root: that root lives in the OS
# store but not in certifi, so certifi-based verification fails with
# CERTIFICATE_VERIFY_FAILED — which is what breaks Google token verification in
# auth.google_login. Injecting truststore here (before any TLS client is
# created) fixes it process-wide for every entry point that imports settings.
try:
    import truststore
    truststore.inject_into_ssl()
except ImportError:
    # Optional: environments without HTTPS interception work fine on certifi.
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Load KEY=VALUE lines from a .env file into os.environ.

    Existing environment variables win, so real env vars still override the
    file. Kept dependency-free (no python-dotenv needed).
    """
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set SECRET_KEY in the environment (Cloud Run env var). The
# insecure fallback is only for local development.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-z=&t-t!s2zn3c3u-9y6)3pw5k1dd*4z!n)4*&=-#26drowfr!5',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True locally; set DEBUG=0 (or leave unset) in production.
DEBUG = os.environ.get('DEBUG', '1') == '1'

# Hosts allowed to serve this app. In production, set ALLOWED_HOSTS to a
# comma-separated list including the Cloud Run host, e.g.
# ALLOWED_HOSTS=myapp-abc123.run.app  (or a custom domain).
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

INTERNAL_IPS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'myapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production (Django doesn't on its own).
    # Must come right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses DATABASE_URL if set (e.g. Neon Postgres in production), otherwise falls
# back to the local SQLite file for development. conn_max_age keeps connections
# alive between requests; ssl_require forces TLS for the managed Postgres.
import dj_database_url  # noqa: E402

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        ssl_require=os.environ.get('DATABASE_URL', '').startswith('postgres'),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Where collectstatic gathers files for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Compress and cache-bust static files. WhiteNoise serves them efficiently.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Frontend origins allowed to call the API with credentials. Locally this is
# the Vite dev server; in production add your Vercel URL via CORS_ALLOWED_ORIGINS
# (comma-separated), e.g. https://solveki.vercel.app
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:5173'
    ).split(',')
    if origin.strip()
]

# The SPA sends the session cookie cross-origin, so credentials must be allowed.
CORS_ALLOW_CREDENTIALS = True

# Session cookie config. In production the SPA (Vercel) and API (Cloud Run) are
# on different sites, so the session cookie must be SameSite=None + Secure to be
# sent cross-site. Locally (DEBUG) both are on localhost, so 'Lax' over HTTP works.
SESSION_COOKIE_HTTPONLY = True
if DEBUG:
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True

# Cloud Run terminates TLS at its proxy and forwards the original scheme in this
# header; trust it so Django knows the request was HTTPS (needed for secure
# cookies and correct redirects).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust the Vercel + Cloud Run origins for CSRF (Django 4+ requires scheme).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Google OAuth client ID (from Google Cloud Console). Loaded from .env or env.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')

# Enables the test-only login endpoint (auth/test-login/) used by the end-to-end
# suite to obtain a real session without Google OAuth. OFF by default; the
# endpoint 404s unless this is set, so it can never be reached in production.
# The E2E run sets ENABLE_TEST_LOGIN=1 in the environment.
ENABLE_TEST_LOGIN = os.environ.get('ENABLE_TEST_LOGIN', '') == '1'


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/
#
# Console logging with a timestamped format. The app's own logger (`myapp`)
# level is driven by the LOG_LEVEL env var (DEBUG in dev, INFO in prod is a
# reasonable default), so instrumentation can be dialled up without code edits.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'myapp': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

