# Generated by Django 6.0.4 on 2026-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_add_course_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='generator_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
