from django.core.management.base import BaseCommand
from myapp.models import Topic

# (topic_name, mathgenerator generator name)
TOPICS = [
    ("Addition of two numbers", "addition"),
    ("Subtraction of two numbers", "subtraction"),
    ("Convert minutes to hours and minutes", "minutes_to_hours"),
    ("Multiplication", "multiplication"),
    ("Division", "division"),
    ("Perimeter of Polygons", "perimeter_of_polygons"),
    ("Compare Fractions", "compare_fractions"),
    ("Fraction to Decimal", "fraction_to_decimal"),
    ("Is Prime", "is_prime"),
    ("Is Composite", "is_composite"),
    ("Factors of a number", "factors"),
    ("Fraction Multiplication", "fraction_multiplication"),
    ("Divide Fractions", "divide_fractions"),
    ("Volume of a cube", "volume_cube"),
    ("Volume of a cuboid", "volume_cuboid"),
    ("Absolute difference between two numbers", "absolute_difference"),
    ("Exponentiation", "exponentiation"),
    ("Square", "square"),
    ("Percentage of a number", "percentage"),
    ("Greatest Common Divisor of N Numbers ( GCD / HCF )", "greatest_common_divisor"),
    ("LCM (Least Common Multiple)", "lcm"),
    ("Prime Factors", "prime_factors"),
    ("Common Factors", "common_factors"),
    ("Combine Like Terms", "combine_like_terms"),
    ("Area of Triangle", "area_of_triangle"),
    ("Surface area of a cube", "surface_area_cube"),
    ("Surface area of a cuboid", "surface_area_cuboid"),
    ("Mean and Median", "mean_median"),
    ("Basic Algebra", "basic_algebra"),
    ("Complementary and Supplementary Angle", "complementary_and_supplementary_angle"),
    ("Third Angle of Triangle", "third_angle_of_triangle"),
    ("Fourth Angle of Quadrilateral", "fourth_angle_of_quadrilateral"),
    ("Area of Circle", "area_of_circle"),
    ("Circumference of Circle", "circumference"),
    ("Area of Circle given center and a point on circle", "area_of_circle_given_center_and_point"),
    ("Surface area of a cone", "surface_area_cone"),
    ("Surface area of a cylinder", "surface_area_cylinder"),
    ("Curved surface area of a cylinder", "curved_surface_area_cylinder"),
    ("Surface area of a pyramid", "surface_area_pyramid"),
    ("Simple Interest", "simple_interest"),
    ("Profit or Loss Percent", "profit_loss_percent"),
    ("Celsius to Fahrenheit", "celsius_to_fahrenheit"),
    ("Percentage difference between two numbers", "percentage_difference"),
    ("Percentage error", "percentage_error"),
    ("Probability of a certain sum appearing on faces of dice", "dice_sum_probability"),
    ("Square Root", "square_root"),
    ("Cube Root", "cube_root"),
    ("Product of scientific notations", "product_of_scientific_notations"),
    ("Pythagorean Theorem", "pythagorean_theorem"),
    ("Volume of a cylinder", "volume_cylinder"),
    ("Volume of a cone", "volume_cone"),
    ("Volume of a sphere", "volume_sphere"),
    ("Volume of a hemisphere", "volume_hemisphere"),
    ("Surface area of a sphere", "surface_area_sphere"),
    ("Solve a System of Equations in R^2", "system_of_equations"),
    ("Linear Equations", "linear_equations"),
    ("Power of Powers", "power_of_powers"),
    ("Quotient of Powers with Same Base", "quotient_of_power_same_base"),
    ("Quotient of Powers with Same Power", "quotient_of_power_same_power"),
    ("Comparing Surds", "surds_comparison"),
    ("Expanding Factored Binomial", "expanding"),
    ("Factoring Quadratic", "factoring"),
    ("Quadratic Equation", "quadratic_equation"),
    ("Intersection of two lines", "intersection_of_two_lines"),
    ("Equation of Line from Two Points", "equation_of_line_from_two_points"),
    ("Compound Interest", "compound_interest"),
    ("Arithmetic Progression Sum", "arithmetic_progression_sum"),
    ("Arithmetic Progression Term", "arithmetic_progression_term"),
    ("Geometric Progression", "geometric_progression"),
    ("Mean, Standard Deviation and Variance", "data_summary"),
    ("Distance between 2 points", "distance_two_points"),
    ("Midpoint of two points", "midpoint_of_two_points"),
    ("Trigonometric Values", "basic_trigonometry"),
    ("Arc length of Angle", "arc_length"),
    ("Area of a Sector", "sector_area"),
    ("Degrees to Radians", "degree_to_rad"),
    ("Radians to Degrees", "radian_to_deg"),
    ("Sum of Angles of Polygon", "sum_of_polygon_angles"),
    ("Angle of a Regular Polygon", "angle_regular_polygon"),
    ("Valid Triangle", "valid_triangle"),
    ("Volume of a pyramid", "volume_pyramid"),
    ("Logarithm", "log"),
    ("Complex Quadratic Equation", "complex_quadratic"),
    ("Multiplication of 2 complex numbers", "multiply_complex_numbers"),
    ("Determinant to 2x2 Matrix", "int_matrix_22_determinant"),
    ("Multiply Two Matrices", "matrix_multiplication"),
    ("Multiply Integer to 2x2 Matrix", "multiply_int_to_22_matrix"),
    ("Invert Matrix", "invert_matrix"),
    ("Average Rate of Change over Interval", "aroc_over_interval"),
    ("Factorial", "factorial"),
    ("Union, Intersection, Difference of Two Sets", "set_operation"),
    ("Combinations of Objects", "combinations"),
    ("Permutations", "permutation"),
    ("Conditional Probability", "conditional_probability"),
    ("Binomial distribution", "binomial_distribution"),
    ("Confidence interval For sample S", "confidence_interval"),
    ("Angle between 2 vectors", "angle_btw_vectors"),
    ("Angle Sum", "angle_sum"),
    ("Dot product of 2 vectors", "vector_dot"),
    ("Cross product of 2 vectors", "vector_cross"),
    ("Euclidian norm or L2 norm of a vector", "euclidian_norm"),
    ("Complex to polar form", "complex_to_polar"),
    ("Power Rule Differentiation", "power_rule_differentiation"),
    ("Power Rule Integration", "power_rule_integration"),
    ("Definite Integral of Quadratic Equation", "definite_integral"),
    ("Stationary Points", "stationary_points"),
    ("Trigonometric Differentiation", "trig_differentiation"),
    ("Vertex of a Quadratic in Vertex Form", "vertex_form"),
    # --- Solveki-local generators added to close Georgia 2023 curriculum gaps ---
    # Grades 1-5 (arithmetic)
    ("Place Value", "arith_place_value"),
    ("Rounding", "arith_rounding"),
    ("Add Fractions", "arith_add_fractions"),
    ("Subtract Fractions", "arith_subtract_fractions"),
    ("Compare Decimals", "arith_compare_decimals"),
    ("Add Decimals", "arith_add_decimals"),
    ("Subtract Decimals", "arith_subtract_decimals"),
    ("Multiply Decimals", "arith_multiply_decimals"),
    ("Order of Operations", "arith_order_of_operations"),
    ("Nth Multiple of a Number", "arith_nth_multiple"),
    ("Powers of Ten", "arith_powers_of_ten"),
    ("Length Unit Conversion", "arith_length_conversion"),
    ("Elapsed Time", "arith_elapsed_time"),
    ("Add and Subtract Money", "arith_money"),
    ("Area of a Rectangle", "arith_area_of_rectangle"),
    # Grades 6-8 (pre-algebra)
    ("Unit Rate", "pre_unit_rate"),
    ("Equivalent Ratios", "pre_equivalent_ratio"),
    ("Solve a Proportion", "pre_solve_proportion"),
    ("Signed Integer Operations", "pre_integer_operations"),
    ("Signed Fraction Operations", "pre_rational_operations"),
    ("Absolute Value Expression", "pre_absolute_value"),
    ("One-Step Inequality", "pre_one_step_inequality"),
    ("Multi-Step Inequality", "pre_multi_step_inequality"),
    ("Scientific Notation Operations", "pre_scientific_notation_ops"),
    ("Integer Exponent Rules", "pre_integer_exponent_rules"),
    ("Constant of Proportionality", "pre_constant_of_proportionality"),
    ("Evaluate a Function", "pre_evaluate_function"),
    ("Slope from Two Points", "pre_slope_from_two_points"),
    ("Linear Function Value", "pre_linear_function_value"),
    ("Mean Absolute Deviation", "pre_mean_absolute_deviation"),
    ("Interquartile Range", "pre_interquartile_range"),
    ("Approximate an Irrational Square Root", "pre_approximate_irrational"),
    # Algebra: Concepts & Connections
    ("Absolute Value Equation", "alg1_absolute_value_equation"),
    ("Exponential Growth and Decay", "alg1_exponential_growth_decay"),
    ("Evaluate an Exponential Function", "alg1_evaluate_exponential"),
    ("Domain of a Function", "alg1_domain_of_function"),
    ("Discriminant and Number of Real Roots", "alg1_discriminant"),
    ("Axis of Symmetry of a Parabola", "alg1_axis_of_symmetry"),
    ("Sum and Product of the Roots", "alg1_sum_product_roots"),
    ("Solve a Linear Inequality", "alg1_linear_inequality_solve"),
    # Advanced Algebra: Concepts & Connections
    ("Evaluate a Polynomial", "alg2_evaluate_polynomial"),
    ("Polynomial Division by a Linear Factor", "alg2_polynomial_division"),
    ("Remainder Theorem", "alg2_remainder_theorem"),
    ("Build a Polynomial from Its Roots", "alg2_build_polynomial_from_roots"),
    ("Add and Subtract Complex Numbers", "alg2_add_complex"),
    ("Rational Exponents", "alg2_rational_exponent"),
    ("Solve a Radical Equation", "alg2_solve_radical_equation"),
    ("Solve an Exponential Equation with Logarithms", "alg2_solve_exponential_log"),
    ("Evaluate a Logarithm", "alg2_evaluate_log"),
    ("Inverse of a Linear Function", "alg2_inverse_linear_function"),
    ("Z-Score of a Data Value", "alg2_z_score"),
    ("Empirical Rule (68-95-99.7)", "alg2_empirical_rule"),
    ("Solve a 2x2 Linear System", "alg2_solve_system_matrix"),
    # Geometry: Concepts & Connections
    ("Right Triangle Side with Trigonometry", "geo_right_triangle_side"),
    ("Right Triangle Side with the Pythagorean Theorem", "geo_solve_right_triangle_pythag"),
    ("Equation of a Circle from Center and Radius", "geo_circle_equation_from_center_radius"),
    ("Center and Radius from a Circle Equation", "geo_circle_center_radius_from_equation"),
    ("Translate a Point", "geo_translate_point"),
    ("Reflect a Point", "geo_reflect_point"),
    ("Rotate a Point", "geo_rotate_point"),
    ("Dilate a Point", "geo_dilate_point"),
    ("Inscribed Angle Theorem", "geo_inscribed_angle"),
    ("Conditional Probability from a Two-Way Table", "geo_conditional_probability_table"),
    ("Compound Probability of Independent Events", "geo_compound_probability"),
    ("Expected Value of a Discrete Distribution", "geo_expected_value"),
    # Statistical Reasoning
    ("Five-Number Summary", "stat_five_number_summary"),
    ("Z-Score", "stat_z_score"),
    ("Correlation Coefficient", "stat_correlation_coefficient"),
    ("Least-Squares Regression Line", "stat_regression_line"),
    ("Margin of Error", "stat_margin_of_error"),
    ("Standard Error of the Mean", "stat_standard_error_mean"),
    ("Sample Proportion Confidence Interval", "stat_sample_proportion_ci"),
    ("Relative Frequency", "stat_relative_frequency"),
    # Precalculus
    ("Law of Sines", "pc_law_of_sines"),
    ("Law of Cosines", "pc_law_of_cosines_side"),
    ("Area of an Oblique Triangle", "pc_oblique_triangle_area"),
    ("Inverse Trigonometric Values", "pc_inverse_trig"),
    ("Double-Angle Values", "pc_double_angle"),
    ("Solve a Trigonometric Equation", "pc_solve_trig_equation"),
    ("Polar to Rectangular Coordinates", "pc_polar_to_rectangular"),
    ("Rectangular to Polar Coordinates", "pc_rectangular_to_polar"),
    ("Finite Geometric Series Sum", "pc_finite_geometric_sum"),
    ("Sigma-Notation Arithmetic Sum", "pc_sigma_arithmetic_sum"),
    ("Limit of a Rational Sequence", "pc_sequence_limit"),
    ("Vector Operations (2D)", "pc_vector_add"),
    ("Eliminate the Parameter", "pc_parametric_to_rectangular"),
    # Calculus
    ("Limit of a Rational Function", "calc_limit_rational"),
    ("Derivative of a Polynomial", "calc_derivative_polynomial"),
    ("Product Rule at a Point", "calc_product_rule"),
    ("Quotient Rule at a Point", "calc_quotient_rule"),
    ("Chain Rule at a Point", "calc_chain_rule"),
    ("Derivative of Exponential, Log, or Trig Function", "calc_derivative_exp_log_trig"),
    ("Higher-Order Derivative at a Point", "calc_higher_order_derivative"),
    ("Tangent Line to a Polynomial", "calc_tangent_line"),
    ("Critical Points and Extrema", "calc_extrema"),
    ("Inflection Point of a Cubic", "calc_inflection_point"),
    ("Definite Integral of a Polynomial", "calc_definite_integral_poly"),
    ("Indefinite Integral of a Polynomial", "calc_indefinite_integral_poly"),
    ("Definite Integral by u-Substitution", "calc_usub_integral"),
    ("Area Between Curves", "calc_area_between_curves"),
    ("Average Value of a Function", "calc_average_value"),
    ("Riemann Sum", "calc_riemann_sum"),
]


class Command(BaseCommand):
    help = "Seed Topic objects for all mathgenerator functions assigned to a Georgia GSE course"

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for name, generator_name in TOPICS:
            topic, was_created = Topic.objects.get_or_create(
                topic_name=name, defaults={"generator_name": generator_name}
            )
            if was_created:
                created += 1
            elif topic.generator_name != generator_name:
                topic.generator_name = generator_name
                topic.save(update_fields=["generator_name"])
                updated += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {created} topic(s) created, {updated} topic(s) updated."
            )
        )
