from django.core.management.base import BaseCommand
from myapp.models import Course, Topic

CURRICULUM = [
    ("Grade 1", 1, [
        "Addition of two numbers",
        "Subtraction of two numbers",
        "Place Value",
        "Compare Numbers",
        "Missing Number in a Sequence",
        "Even or Odd",
        "Ordinal Numbers",
        "Add and Subtract Word Problem within 20",
    ]),
    ("Grade 2", 2, [
        "Convert minutes to hours and minutes",
        "Elapsed Time",
        "Add and Subtract Money",
        "Add and Subtract within 1000",
        "Tell Time to the Nearest 5 Minutes",
        "Count Money Value",
        "Arrays and Repeated Addition",
        "Compare 3-Digit Numbers",
    ]),
    ("Grade 3", 3, [
        "Multiplication",
        "Division",
        "Perimeter of Polygons",
        "Rounding",
        "Area of a Rectangle",
        "Equivalent Fractions",
        "Missing Factor",
        "Fraction on a Number Line",
        "Two-Step Word Problem",
    ]),
    ("Grade 4", 4, [
        "Compare Fractions",
        "Fraction to Decimal",
        "Is Prime",
        "Is Composite",
        "Factors of a number",
        "Add Fractions",
        "Subtract Fractions",
        "Compare Decimals",
        "Add Decimals",
        "Subtract Decimals",
        "Nth Multiple of a Number",
        "Multiply a Fraction by a Whole Number",
        "Mixed and Improper Fractions",
        "Long Division with Remainder",
        "Angle Addition",
        "Factor Pairs Count",
    ]),
    ("Grade 5", 5, [
        "Fraction Multiplication",
        "Divide Fractions",
        "Volume of a cube",
        "Volume of a cuboid",
        "Multiply Decimals",
        "Order of Operations",
        "Powers of Ten",
        "Length Unit Conversion",
        "Add and Subtract Unlike Denominators",
        "Round Decimals",
        "Metric Unit Conversion",
        "Divide Decimals",
    ]),
    ("Grade 6", 6, [
        "Absolute difference between two numbers",
        "Exponentiation",
        "Square",
        "Percentage of a number",
        "Greatest Common Divisor of N Numbers ( GCD / HCF )",
        "LCM (Least Common Multiple)",
        "Prime Factors",
        "Common Factors",
        "Combine Like Terms",
        "Area of Triangle",
        "Area of Trapezoid",
        "Surface area of a cube",
        "Surface area of a cuboid",
        "Mean and Median",
        "Unit Rate",
        "Equivalent Ratios",
        "Signed Integer Operations",
        "Signed Fraction Operations",
        "Absolute Value Expression",
        "One-Step Inequality",
        "Mean Absolute Deviation",
        "Interquartile Range",
        "Range of a Data Set",
        "Mode of a Data Set",
        "Convert Between Fractions, Decimals, and Percents",
        "Evaluate an Algebraic Expression",
        "Distributive Property",
        "Order Rational Numbers",
        "Coordinate Distance",
    ]),
    ("Grade 7", 7, [
        "Basic Algebra",
        "Complementary and Supplementary Angle",
        "Third Angle of Triangle",
        "Fourth Angle of Quadrilateral",
        "Area of Circle",
        "Circumference of Circle",
        "Area of Circle given center and a point on circle",
        "Surface area of a cone",
        "Surface area of a cylinder",
        "Curved surface area of a cylinder",
        "Surface area of a pyramid",
        "Simple Interest",
        "Profit or Loss Percent",
        "Celsius to Fahrenheit",
        "Percentage difference between two numbers",
        "Percentage error",
        "Probability of a certain sum appearing on faces of dice",
        "Solve a Proportion",
        "Multi-Step Inequality",
        "Constant of Proportionality",
        "Two-Step Equation",
        "Multi-Step Equation",
        "Percent Increase or Decrease",
        "Discount, Tax, and Tip",
        "Scale Factor Length",
        "Probability of Compound Events",
    ]),
    ("Grade 8", 8, [
        "Square Root",
        "Cube Root",
        "Product of scientific notations",
        "Pythagorean Theorem",
        "Volume of a cylinder",
        "Volume of a cone",
        "Volume of a sphere",
        "Volume of a hemisphere",
        "Surface area of a sphere",
        "Solve a System of Equations in R^2",
        "Linear Equations",
        "Scientific Notation Operations",
        "Integer Exponent Rules",
        "Evaluate a Function",
        "Slope from Two Points",
        "Linear Function Value",
        "Approximate an Irrational Square Root",
        "Translate a Point",
        "Reflect a Point",
        "Rotate a Point",
        "Dilate a Point",
        "Variables on Both Sides",
        "Slope-Intercept Form from Standard Form",
        "Line from Slope and a Point",
        "Compare Two Functions",
        "Number of Solutions of a Linear System",
    ]),
    ("Algebra I", 9, [
        "Simplify Square Root",
        "Power of Powers",
        "Quotient of Powers with Same Base",
        "Quotient of Powers with Same Power",
        "Comparing Surds",
        "Expanding Factored Binomial",
        "Factoring Quadratic",
        "Quadratic Equation",
        "Vertex of a Quadratic in Vertex Form",
        "Intersection of two lines",
        "Equation of Line from Two Points",
        "Compound Interest",
        "Arithmetic Progression Sum",
        "Arithmetic Progression Term",
        "Geometric Progression",
        "Absolute Value Equation",
        "Exponential Growth and Decay",
        "Evaluate an Exponential Function",
        "Domain of a Function",
        "Discriminant and Number of Real Roots",
        "Axis of Symmetry of a Parabola",
        "Sum and Product of the Roots",
        "Solve a Linear Inequality",
        "Product of Powers with the Same Base",
        "Power of a Product",
        "Negative Exponents",
        "Completing the Square",
        "Solve a Literal Equation",
        "Point-Slope Form",
        "Multiply Binomials",
        "Solve a System of Equations",
        "Direct and Inverse Variation",
        "Simplify a Rational Expression",
        "Absolute-Value Inequality",
    ]),
    ("Geometry", 10, [
        "Distance between 2 points",
        "Midpoint of two points",
        "Arc length of Angle",
        "Area of a Sector",
        "Degrees to Radians",
        "Radians to Degrees",
        "Sum of Angles of Polygon",
        "Angle of a Regular Polygon",
        "Valid Triangle",
        "Volume of a pyramid",
        "Volume of the frustum of a cone",
        "Right Triangle Side with Trigonometry",
        "Right Triangle Side with the Pythagorean Theorem",
        "Equation of a Circle from Center and Radius",
        "Center and Radius from a Circle Equation",
        "Inscribed Angle Theorem",
        "Conditional Probability from a Two-Way Table",
        "Compound Probability of Independent Events",
        "Expected Value of a Discrete Distribution",
        "Special Right Triangles",
        "Similar Triangles Missing Side",
        "Scale Factor to Area or Volume Ratio",
        "Segment Lengths in Circles",
        "Area of a Regular Polygon",
        "Composite Solid Volume",
        "Polygon Area from Vertices",
    ]),
    ("Algebra II", 11, [
        "Logarithm",
        "Multiplication of 2 complex numbers",
        "Determinant to 2x2 Matrix",
        "Average Rate of Change over Interval",
        "Factorial",
        "Combinations of Objects",
        "Permutations",
        "Evaluate a Polynomial",
        "Polynomial Division by a Linear Factor",
        "Remainder Theorem",
        "Build a Polynomial from Its Roots",
        "Add and Subtract Complex Numbers",
        "Rational Exponents",
        "Solve a Radical Equation",
        "Solve an Exponential Equation with Logarithms",
        "Evaluate a Logarithm",
        "Inverse of a Linear Function",
        "Z-Score of a Data Value",
        "Empirical Rule (68-95-99.7)",
        "Solve a 2x2 Linear System",
        "Union, Intersection, Difference of Two Sets",
        "Logarithm Product Rule",
        "Logarithm Quotient Rule",
        "Logarithm Power Rule",
        "Change of Base Formula",
        "Rationalize a Denominator Using the Conjugate",
        "Solve a Radical Equation Using the Conjugate",
        "Function Composition",
        "Solve a Rational Equation",
        "Rational Expression Operations",
        "Complex Number Division",
        "Modulus of a Complex Number",
        "Inverse of a Non-Linear Function",
        "Rational Root Theorem",
        "System of Three Equations",
        "Matrix Operation (2x2)",
        "Solve a Polynomial by Factoring",
        "Conic Equation from Features",
        "End Behavior of a Polynomial",
    ]),
    ("Statistical Reasoning", 12, [
        "Mean, Standard Deviation and Variance",
        "Conditional Probability",
        "Binomial distribution",
        "Confidence interval For sample S",
        "Five-Number Summary",
        "Z-Score",
        "Correlation Coefficient",
        "Least-Squares Regression Line",
        "Margin of Error",
        "Standard Error of the Mean",
        "Sample Proportion Confidence Interval",
        "Relative Frequency",
        "Normal Distribution Probability",
        "Test Statistic for a Mean or Proportion",
        "Expected Value and Variance",
        "Percentile Rank",
        "Counting to Probability",
        "Odds from Probability",
    ]),
    ("Pre-Calculus", 12, [
        "Angle Sum",
        "Angle between 2 vectors",
        "Dot product of 2 vectors",
        "Orthogonal Projection",
        "Euclidian norm or L2 norm of a vector",
        "Complex to polar form",
        "Law of Sines",
        "Law of Cosines",
        "Area of an Oblique Triangle",
        "Inverse Trigonometric Values",
        "Double-Angle Values",
        "Solve a Trigonometric Equation",
        "Polar to Rectangular Coordinates",
        "Rectangular to Polar Coordinates",
        "Finite Geometric Series Sum",
        "Sigma-Notation Arithmetic Sum",
        "Limit of a Rational Sequence",
        "Vector Operations (2D)",
        "Eliminate the Parameter",
        "Coordinates on the Unit Circle",
        "Sine on the Unit Circle",
        "Cosine on the Unit Circle",
        "Tangent on the Unit Circle",
        "Quadratic-Form Trigonometric Equation",
        "Vertical Asymptotes of a Rational Function",
        "Zeros of a Rational Function",
        "Holes of a Rational Function",
        "Horizontal Asymptote of a Rational Function",
        "Slant Asymptote of a Rational Function",
        "Y-Intercept of a Rational Function",
        "Rational Inequality",
        "Sinusoid Features",
        "Sum and Difference Formula Values",
        "Half-Angle Formula Values",
        "Binomial Theorem Term",
        "De Moivre's Theorem",
        "Simplify Using Trig Identities",
        "Recursive Sequence Nth Term",
        "Partial Fraction Decomposition",
        "Polar and Rectangular Equation Conversion",
    ]),
    ("AP Calculus", 12, [
        "Power Rule Differentiation",
        "Power Rule Integration",
        "Definite Integral of Quadratic Equation",
        "Trigonometric Differentiation",
        "Limit of a Rational Function",
        "Limit Using the Conjugate",
        "Derivative of a Polynomial",
        "Product Rule at a Point",
        "Quotient Rule at a Point",
        "Chain Rule at a Point",
        "Derivative of Exponential, Log, or Trig Function",
        "Higher-Order Derivative at a Point",
        "Tangent Line to a Polynomial",
        "Critical Points and Extrema",
        "Inflection Point of a Cubic",
        "Definite Integral of a Polynomial",
        "Indefinite Integral of a Polynomial",
        "Definite Integral by u-Substitution",
        "Area Between Curves",
        "Average Value of a Function",
        "Riemann Sum",
        "Implicit Differentiation",
        "Particle Motion",
        "Volume of a Solid of Revolution",
        "L'Hopital's Rule",
        "Derivative Using the Limit Definition",
        "Integration by Parts",
        "Related Rates",
        "Mean Value Theorem",
        "Trapezoidal Rule",
        "Separable Differential Equation",
        "Concavity Interval",
        "Taylor/Maclaurin Coefficient",
    ]),
]


class Command(BaseCommand):
    help = "Seed Course objects and link existing Topics to their courses"

    def handle(self, *args, **options):
        courses_created = 0
        topics_linked = 0
        topics_missing = []

        for course_name, grade_level, topic_names in CURRICULUM:
            course, created = Course.objects.get_or_create(
                course_name=course_name,
                defaults={"grade_level": grade_level},
            )
            if created:
                courses_created += 1

            for name in topic_names:
                try:
                    topic = Topic.objects.get(topic_name=name)
                    topic.course = course
                    topic.save()
                    topics_linked += 1
                except Topic.DoesNotExist:
                    topics_missing.append(name)

        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {courses_created} course(s) created, {topics_linked} topic(s) linked."
            )
        )
        if topics_missing:
            self.stdout.write(
                self.style.WARNING(f"Topics not found: {topics_missing}")
            )
