from django.core.management.base import BaseCommand
from myapp.models import Topic

# (topic_name, mathgenerator generator name)
TOPICS = [
    ("Addition of two numbers", "addition"),
    ("Subtraction of two numbers", "subtraction"),
    ("Convert minutes to hours and minutes", "arith_minutes_to_hours"),
    ("Multiplication", "multiplication"),
    ("Division", "division"),
    ("Perimeter of Polygons", "perimeter_of_polygons"),
    ("Compare Fractions", "compare_fractions"),
    ("Fraction to Decimal", "fraction_to_decimal"),
    ("Is Prime", "is_prime"),
    ("Is Composite", "is_composite"),
    ("Factors of a number", "factors"),
    ("Fraction Multiplication", "fraction_multiplication"),
    ("Divide Fractions", "divide_fractions"),
    ("Volume of a cube", "volume_cube"),
    ("Volume of a cuboid", "volume_cuboid"),
    ("Absolute difference between two numbers", "absolute_difference"),
    ("Exponentiation", "exponentiation"),
    ("Square", "square"),
    ("Percentage of a number", "percentage"),
    ("Greatest Common Divisor of N Numbers ( GCD / HCF )", "greatest_common_divisor"),
    ("LCM (Least Common Multiple)", "lcm"),
    ("Prime Factors", "prime_factors"),
    ("Common Factors", "common_factors"),
    ("Combine Like Terms", "combine_like_terms"),
    ("Area of Triangle", "area_of_triangle"),
    ("Surface area of a cube", "surface_area_cube"),
    ("Surface area of a cuboid", "surface_area_cuboid"),
    ("Mean and Median", "mean_median"),
    ("Basic Algebra", "basic_algebra"),
    ("Complementary and Supplementary Angle", "complementary_and_supplementary_angle"),
    ("Third Angle of Triangle", "third_angle_of_triangle"),
    ("Fourth Angle of Quadrilateral", "fourth_angle_of_quadrilateral"),
    ("Area of Circle", "area_of_circle"),
    ("Circumference of Circle", "circumference"),
    ("Area of Circle given center and a point on circle", "area_of_circle_given_center_and_point"),
    ("Surface area of a cone", "surface_area_cone"),
    ("Surface area of a cylinder", "surface_area_cylinder"),
    ("Curved surface area of a cylinder", "curved_surface_area_cylinder"),
    ("Surface area of a pyramid", "surface_area_pyramid"),
    ("Simple Interest", "simple_interest"),
    ("Profit or Loss Percent", "profit_loss_percent"),
    ("Celsius to Fahrenheit", "celsius_to_fahrenheit"),
    ("Percentage difference between two numbers", "percentage_difference"),
    ("Percentage error", "percentage_error"),
    ("Probability of a certain sum appearing on faces of dice", "dice_sum_probability"),
    ("Square Root", "square_root"),
    ("Cube Root", "cube_root"),
    ("Product of scientific notations", "product_of_scientific_notations"),
    ("Pythagorean Theorem", "pythagorean_theorem"),
    ("Volume of a cylinder", "volume_cylinder"),
    ("Volume of a cone", "volume_cone"),
    ("Volume of a sphere", "volume_sphere"),
    ("Volume of a hemisphere", "volume_hemisphere"),
    ("Surface area of a sphere", "surface_area_sphere"),
    ("Solve a System of Equations in R^2", "system_of_equations"),
    ("Linear Equations", "linear_equations"),
    ("Power of Powers", "power_of_powers"),
    ("Quotient of Powers with Same Base", "quotient_of_power_same_base"),
    ("Quotient of Powers with Same Power", "quotient_of_power_same_power"),
    ("Comparing Surds", "surds_comparison"),
    ("Expanding Factored Binomial", "expanding"),
    ("Factoring Quadratic", "factoring"),
    ("Quadratic Equation", "quadratic_equation"),
    ("Intersection of two lines", "intersection_of_two_lines"),
    ("Equation of Line from Two Points", "equation_of_line_from_two_points"),
    ("Compound Interest", "compound_interest"),
    ("Arithmetic Progression Sum", "arithmetic_progression_sum"),
    ("Arithmetic Progression Term", "arithmetic_progression_term"),
    ("Geometric Progression", "geometric_progression"),
    ("Mean, Standard Deviation and Variance", "data_summary"),
    ("Distance between 2 points", "distance_two_points"),
    ("Midpoint of two points", "midpoint_of_two_points"),
    ("Arc length of Angle", "arc_length"),
    ("Area of a Sector", "sector_area"),
    ("Degrees to Radians", "degree_to_rad"),
    ("Radians to Degrees", "radian_to_deg"),
    ("Sum of Angles of Polygon", "sum_of_polygon_angles"),
    ("Angle of a Regular Polygon", "angle_regular_polygon"),
    ("Valid Triangle", "valid_triangle"),
    ("Volume of a pyramid", "volume_pyramid"),
    ("Logarithm", "log"),
    ("Multiplication of 2 complex numbers", "multiply_complex_numbers"),
    ("Determinant to 2x2 Matrix", "int_matrix_22_determinant"),
    ("Average Rate of Change over Interval", "aroc_over_interval"),
    ("Factorial", "factorial"),
    ("Combinations of Objects", "combinations"),
    ("Permutations", "permutation"),
    ("Conditional Probability", "conditional_probability"),
    ("Binomial distribution", "binomial_distribution"),
    ("Confidence interval For sample S", "confidence_interval"),
    ("Angle between 2 vectors", "angle_btw_vectors"),
    ("Angle Sum", "angle_sum"),
    ("Dot product of 2 vectors", "vector_dot"),
    ("Euclidian norm or L2 norm of a vector", "euclidian_norm"),
    ("Complex to polar form", "complex_to_polar"),
    ("Power Rule Differentiation", "power_rule_differentiation"),
    ("Power Rule Integration", "power_rule_integration"),
    ("Definite Integral of Quadratic Equation", "definite_integral"),
    ("Trigonometric Differentiation", "trig_differentiation"),
    ("Vertex of a Quadratic in Vertex Form", "vertex_form"),
    ("Union, Intersection, Difference of Two Sets", "set_operation"),
    # --- Solveki-local generators added to close Georgia 2023 curriculum gaps ---
    # Grades 1-5 (arithmetic)
    ("Place Value", "arith_place_value"),
    ("Rounding", "arith_rounding"),
    ("Add Fractions", "arith_add_fractions"),
    ("Subtract Fractions", "arith_subtract_fractions"),
    ("Compare Decimals", "arith_compare_decimals"),
    ("Add Decimals", "arith_add_decimals"),
    ("Subtract Decimals", "arith_subtract_decimals"),
    ("Multiply Decimals", "arith_multiply_decimals"),
    ("Order of Operations", "arith_order_of_operations"),
    ("Nth Multiple of a Number", "arith_nth_multiple"),
    ("Powers of Ten", "arith_powers_of_ten"),
    ("Length Unit Conversion", "arith_length_conversion"),
    ("Elapsed Time", "arith_elapsed_time"),
    ("Add and Subtract Money", "arith_money"),
    ("Area of a Rectangle", "arith_area_of_rectangle"),
    # Grades 6-8 (pre-algebra)
    ("Unit Rate", "pre_unit_rate"),
    ("Equivalent Ratios", "pre_equivalent_ratio"),
    ("Solve a Proportion", "pre_solve_proportion"),
    ("Signed Integer Operations", "pre_integer_operations"),
    ("Signed Fraction Operations", "pre_rational_operations"),
    ("Absolute Value Expression", "pre_absolute_value"),
    ("One-Step Inequality", "pre_one_step_inequality"),
    ("Multi-Step Inequality", "pre_multi_step_inequality"),
    ("Scientific Notation Operations", "pre_scientific_notation_ops"),
    ("Integer Exponent Rules", "pre_integer_exponent_rules"),
    ("Constant of Proportionality", "pre_constant_of_proportionality"),
    ("Evaluate a Function", "pre_evaluate_function"),
    ("Slope from Two Points", "pre_slope_from_two_points"),
    ("Linear Function Value", "pre_linear_function_value"),
    ("Mean Absolute Deviation", "pre_mean_absolute_deviation"),
    ("Interquartile Range", "pre_interquartile_range"),
    ("Range of a Data Set", "pre_range"),
    ("Mode of a Data Set", "pre_mode"),
    ("Approximate an Irrational Square Root", "pre_approximate_irrational"),
    # Algebra: Concepts & Connections
    ("Absolute Value Equation", "alg1_absolute_value_equation"),
    ("Product of Powers with the Same Base", "alg1_product_of_powers"),
    ("Power of a Product", "alg1_power_of_product"),
    ("Negative Exponents", "alg1_negative_exponent"),
    ("Exponential Growth and Decay", "alg1_exponential_growth_decay"),
    ("Evaluate an Exponential Function", "alg1_evaluate_exponential"),
    ("Domain of a Function", "alg1_domain_of_function"),
    ("Discriminant and Number of Real Roots", "alg1_discriminant"),
    ("Axis of Symmetry of a Parabola", "alg1_axis_of_symmetry"),
    ("Sum and Product of the Roots", "alg1_sum_product_roots"),
    ("Solve a Linear Inequality", "alg1_linear_inequality_solve"),
    # Advanced Algebra: Concepts & Connections
    ("Evaluate a Polynomial", "alg2_evaluate_polynomial"),
    ("Polynomial Division by a Linear Factor", "alg2_polynomial_division"),
    ("Remainder Theorem", "alg2_remainder_theorem"),
    ("Build a Polynomial from Its Roots", "alg2_build_polynomial_from_roots"),
    ("Add and Subtract Complex Numbers", "alg2_add_complex"),
    ("Rational Exponents", "alg2_rational_exponent"),
    ("Solve a Radical Equation", "alg2_solve_radical_equation"),
    ("Solve an Exponential Equation with Logarithms", "alg2_solve_exponential_log"),
    ("Evaluate a Logarithm", "alg2_evaluate_log"),
    ("Inverse of a Linear Function", "alg2_inverse_linear_function"),
    ("Z-Score of a Data Value", "alg2_z_score"),
    ("Empirical Rule (68-95-99.7)", "alg2_empirical_rule"),
    ("Solve a 2x2 Linear System", "alg2_solve_system_matrix"),
    ("Logarithm Product Rule", "alg2_log_product_rule"),
    ("Logarithm Quotient Rule", "alg2_log_quotient_rule"),
    ("Logarithm Power Rule", "alg2_log_power_rule"),
    ("Change of Base Formula", "alg2_log_change_of_base"),
    ("Rationalize a Denominator Using the Conjugate", "alg2_rationalize_denominator"),
    ("Solve a Radical Equation Using the Conjugate", "alg2_radical_equation_conjugate"),
    # Geometry: Concepts & Connections
    ("Right Triangle Side with Trigonometry", "geo_right_triangle_side"),
    ("Right Triangle Side with the Pythagorean Theorem", "geo_solve_right_triangle_pythag"),
    ("Equation of a Circle from Center and Radius", "geo_circle_equation_from_center_radius"),
    ("Center and Radius from a Circle Equation", "geo_circle_center_radius_from_equation"),
    ("Translate a Point", "geo_translate_point"),
    ("Reflect a Point", "geo_reflect_point"),
    ("Rotate a Point", "geo_rotate_point"),
    ("Dilate a Point", "geo_dilate_point"),
    ("Inscribed Angle Theorem", "geo_inscribed_angle"),
    ("Conditional Probability from a Two-Way Table", "geo_conditional_probability_table"),
    ("Compound Probability of Independent Events", "geo_compound_probability"),
    ("Expected Value of a Discrete Distribution", "geo_expected_value"),
    # Statistical Reasoning
    ("Five-Number Summary", "stat_five_number_summary"),
    ("Z-Score", "stat_z_score"),
    ("Correlation Coefficient", "stat_correlation_coefficient"),
    ("Least-Squares Regression Line", "stat_regression_line"),
    ("Margin of Error", "stat_margin_of_error"),
    ("Standard Error of the Mean", "stat_standard_error_mean"),
    ("Sample Proportion Confidence Interval", "stat_sample_proportion_ci"),
    ("Relative Frequency", "stat_relative_frequency"),
    # Precalculus
    ("Law of Sines", "pc_law_of_sines"),
    ("Law of Cosines", "pc_law_of_cosines_side"),
    ("Area of an Oblique Triangle", "pc_oblique_triangle_area"),
    ("Inverse Trigonometric Values", "pc_inverse_trig"),
    ("Double-Angle Values", "pc_double_angle"),
    ("Solve a Trigonometric Equation", "pc_solve_trig_equation"),
    ("Polar to Rectangular Coordinates", "pc_polar_to_rectangular"),
    ("Rectangular to Polar Coordinates", "pc_rectangular_to_polar"),
    ("Finite Geometric Series Sum", "pc_finite_geometric_sum"),
    ("Sigma-Notation Arithmetic Sum", "pc_sigma_arithmetic_sum"),
    ("Limit of a Rational Sequence", "pc_sequence_limit"),
    ("Vector Operations (2D)", "pc_vector_add"),
    ("Eliminate the Parameter", "pc_parametric_to_rectangular"),
    ("Coordinates on the Unit Circle", "pc_unit_circle_point"),
    ("Sine on the Unit Circle", "pc_unit_circle_sin"),
    ("Cosine on the Unit Circle", "pc_unit_circle_cos"),
    ("Tangent on the Unit Circle", "pc_unit_circle_tan"),
    ("Quadratic-Form Trigonometric Equation", "pc_trig_quadratic"),
    ("Vertical Asymptotes of a Rational Function", "pc_rational_vertical_asymptotes"),
    ("Zeros of a Rational Function", "pc_rational_zeros"),
    ("Holes of a Rational Function", "pc_rational_holes"),
    ("Horizontal Asymptote of a Rational Function", "pc_rational_horizontal_asymptote"),
    ("Slant Asymptote of a Rational Function", "pc_rational_slant_asymptote"),
    ("Y-Intercept of a Rational Function", "pc_rational_y_intercept"),
    ("Rational Inequality", "pc_rational_inequality"),
    # Calculus
    ("Limit of a Rational Function", "calc_limit_rational"),
    ("Limit Using the Conjugate", "calc_limit_conjugate"),
    ("Derivative of a Polynomial", "calc_derivative_polynomial"),
    ("Product Rule at a Point", "calc_product_rule"),
    ("Quotient Rule at a Point", "calc_quotient_rule"),
    ("Chain Rule at a Point", "calc_chain_rule"),
    ("Derivative of Exponential, Log, or Trig Function", "calc_derivative_exp_log_trig"),
    ("Higher-Order Derivative at a Point", "calc_higher_order_derivative"),
    ("Tangent Line to a Polynomial", "calc_tangent_line"),
    ("Critical Points and Extrema", "calc_extrema"),
    ("Inflection Point of a Cubic", "calc_inflection_point"),
    ("Definite Integral of a Polynomial", "calc_definite_integral_poly"),
    ("Indefinite Integral of a Polynomial", "calc_indefinite_integral_poly"),
    ("Definite Integral by u-Substitution", "calc_usub_integral"),
    ("Area Between Curves", "calc_area_between_curves"),
    ("Average Value of a Function", "calc_average_value"),
    ("Riemann Sum", "calc_riemann_sum"),
    # --- Gap-analysis topics: arithmetic (Grades 1-5) ---
    ("Compare Numbers", "arith_compare_numbers"),
    ("Missing Number in a Sequence", "arith_missing_number_sequence"),
    ("Even or Odd", "arith_even_or_odd"),
    ("Ordinal Numbers", "arith_ordinal_number"),
    ("Add and Subtract Word Problem within 20", "arith_word_problem_within_20"),
    ("Add and Subtract within 1000", "arith_add_subtract_within_1000"),
    ("Tell Time to the Nearest 5 Minutes", "arith_tell_time_five_min"),
    ("Count Money Value", "arith_count_money_value"),
    ("Arrays and Repeated Addition", "arith_array_repeated_addition"),
    ("Compare 3-Digit Numbers", "arith_compare_three_digit"),
    ("Equivalent Fractions", "arith_equivalent_fraction"),
    ("Missing Factor", "arith_missing_factor"),
    ("Fraction on a Number Line", "arith_fraction_on_number_line"),
    ("Two-Step Word Problem", "arith_two_step_word_problem"),
    ("Multiply a Fraction by a Whole Number", "arith_fraction_times_whole"),
    ("Mixed and Improper Fractions", "arith_mixed_to_improper"),
    ("Long Division with Remainder", "arith_long_division_remainder"),
    ("Angle Addition", "arith_angle_addition"),
    ("Factor Pairs Count", "arith_factor_pairs_count"),
    ("Add and Subtract Unlike Denominators", "arith_add_unlike_fractions"),
    ("Round Decimals", "arith_round_decimal"),
    ("Metric Unit Conversion", "arith_metric_unit_conversion"),
    ("Divide Decimals", "arith_divide_decimals"),
    # --- Gap-analysis topics: Geometry ---
    ("Special Right Triangles", "geo_special_right_triangle"),
    ("Similar Triangles Missing Side", "geo_similar_triangle_side"),
    ("Scale Factor to Area or Volume Ratio", "geo_scale_factor_ratio"),
    ("Segment Lengths in Circles", "geo_circle_segments"),
    ("Area of a Regular Polygon", "geo_regular_polygon_area"),
    ("Composite Solid Volume", "geo_composite_solid"),
    ("Polygon Area from Vertices", "geo_polygon_area_vertices"),
    # --- Gap-analysis topics: Statistical Reasoning ---
    ("Normal Distribution Probability", "stat_normal_probability"),
    ("Test Statistic for a Mean or Proportion", "stat_test_statistic"),
    ("Expected Value and Variance", "stat_discrete_variance"),
    ("Percentile Rank", "stat_percentile_rank"),
    ("Counting to Probability", "stat_counting_probability"),
    ("Odds from Probability", "stat_odds_probability"),
    # --- Gap-analysis topics: pre-algebra (Grades 6-8) ---
    ("Convert Between Fractions, Decimals, and Percents", "pre_convert_fdp"),
    ("Evaluate an Algebraic Expression", "pre_evaluate_expression"),
    ("Distributive Property", "pre_distributive_property"),
    ("Order Rational Numbers", "pre_order_rational"),
    ("Coordinate Distance", "pre_coordinate_distance"),
    ("Two-Step Equation", "pre_two_step_equation"),
    ("Multi-Step Equation", "pre_multi_step_equation"),
    ("Percent Increase or Decrease", "pre_percent_change"),
    ("Discount, Tax, and Tip", "pre_discount_tax_tip"),
    ("Scale Factor Length", "pre_scale_length"),
    ("Probability of Compound Events", "pre_compound_probability"),
    ("Variables on Both Sides", "pre_variables_both_sides"),
    ("Slope-Intercept Form from Standard Form", "pre_slope_intercept_form"),
    ("Line from Slope and a Point", "pre_line_from_slope_point"),
    ("Compare Two Functions", "pre_compare_functions"),
    ("Number of Solutions of a Linear System", "pre_system_solution_count"),
    # --- Gap-analysis topics: Algebra I ---
    ("Completing the Square", "alg1_complete_the_square"),
    ("Solve a Literal Equation", "alg1_literal_equation"),
    ("Point-Slope Form", "alg1_point_slope_form"),
    ("Multiply Binomials", "alg1_multiply_binomials"),
    ("Solve a System of Equations", "alg1_solve_system"),
    ("Direct and Inverse Variation", "alg1_variation"),
    ("Simplify a Rational Expression", "alg1_simplify_rational"),
    ("Absolute-Value Inequality", "alg1_abs_value_inequality"),
    # --- Gap-analysis topics: Algebra II ---
    ("Function Composition", "alg2_function_composition"),
    ("Solve a Rational Equation", "alg2_solve_rational_equation"),
    ("Rational Expression Operations", "alg2_rational_expression_ops"),
    ("Complex Number Division", "alg2_complex_division"),
    ("Modulus of a Complex Number", "alg2_complex_modulus"),
    ("Inverse of a Non-Linear Function", "alg2_inverse_nonlinear"),
    ("Rational Root Theorem", "alg2_rational_root_list"),
    ("System of Three Equations", "alg2_solve_system_three"),
    ("Matrix Operation (2x2)", "alg2_matrix_operation"),
    ("Solve a Polynomial by Factoring", "alg2_solve_polynomial_factoring"),
    ("Conic Equation from Features", "alg2_conic_equation"),
    ("End Behavior of a Polynomial", "alg2_polynomial_end_behavior"),
    # --- Gap-analysis topics: Pre-Calculus ---
    ("Sinusoid Features", "pc_sinusoid_features"),
    ("Sum and Difference Formula Values", "pc_sum_difference_values"),
    ("Half-Angle Formula Values", "pc_half_angle_values"),
    ("Binomial Theorem Term", "pc_binomial_term"),
    ("De Moivre's Theorem", "pc_de_moivre"),
    ("Simplify Using Trig Identities", "pc_simplify_trig_identity"),
    ("Recursive Sequence Nth Term", "pc_recursive_sequence_term"),
    ("Partial Fraction Decomposition", "pc_partial_fractions"),
    ("Polar and Rectangular Equation Conversion", "pc_polar_rectangular_equation"),
    # --- Gap-analysis topics: AP Calculus ---
    ("Implicit Differentiation", "calc_implicit_differentiation"),
    ("Particle Motion", "calc_particle_motion"),
    ("Volume of a Solid of Revolution", "calc_volume_revolution"),
    ("L'Hopital's Rule", "calc_lhopital"),
    ("Derivative Using the Limit Definition", "calc_limit_definition_derivative"),
    ("Integration by Parts", "calc_integration_by_parts"),
    ("Related Rates", "calc_related_rates"),
    ("Mean Value Theorem", "calc_mvt_find_c"),
    ("Trapezoidal Rule", "calc_trapezoidal_rule"),
    ("Separable Differential Equation", "calc_separable_ode"),
    ("Concavity Interval", "calc_concavity_interval"),
    ("Taylor/Maclaurin Coefficient", "calc_taylor_coefficient"),
    # --- Repair previously-dangling course references ---
    ("Area of Trapezoid", "pre_area_of_trapezoid"),
    ("Volume of the frustum of a cone", "geo_frustum_volume"),
    ("Simplify Square Root", "alg1_simplify_radical"),
    ("Orthogonal Projection", "pc_orthogonal_projection"),
]


class Command(BaseCommand):
    help = "Seed Topic objects for all mathgenerator functions assigned to a Georgia GSE course"

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for name, generator_name in TOPICS:
            topic, was_created = Topic.objects.get_or_create(
                topic_name=name, defaults={"generator_name": generator_name}
            )
            if was_created:
                created += 1
            elif topic.generator_name != generator_name:
                topic.generator_name = generator_name
                topic.save(update_fields=["generator_name"])
                updated += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {created} topic(s) created, {updated} topic(s) updated."
            )
        )
