from django.core.management.base import BaseCommand
from myapp.models import Course, Topic

CURRICULUM = [
    ("Grade 1", 1, [
        "Addition of two numbers",
        "Subtraction of two numbers",
        "Place Value",
    ]),
    ("Grade 2", 2, [
        "Convert minutes to hours and minutes",
        "Elapsed Time",
        "Add and Subtract Money",
    ]),
    ("Grade 3", 3, [
        "Multiplication",
        "Division",
        "Perimeter of Polygons",
        "Rounding",
        "Area of a Rectangle",
    ]),
    ("Grade 4", 4, [
        "Compare Fractions",
        "Fraction to Decimal",
        "Is Prime",
        "Is Composite",
        "Factors of a number",
        "Add Fractions",
        "Subtract Fractions",
        "Compare Decimals",
        "Add Decimals",
        "Subtract Decimals",
        "Nth Multiple of a Number",
    ]),
    ("Grade 5", 5, [
        "Fraction Multiplication",
        "Divide Fractions",
        "Volume of a cube",
        "Volume of a cuboid",
        "Multiply Decimals",
        "Order of Operations",
        "Powers of Ten",
        "Length Unit Conversion",
    ]),
    ("Grade 6", 6, [
        "Absolute difference between two numbers",
        "Exponentiation",
        "Square",
        "Percentage of a number",
        "Greatest Common Divisor of N Numbers ( GCD / HCF )",
        "LCM (Least Common Multiple)",
        "Prime Factors",
        "Common Factors",
        "Combine Like Terms",
        "Area of Triangle",
        "Area of Trapezoid",
        "Surface area of a cube",
        "Surface area of a cuboid",
        "Mean and Median",
        "Unit Rate",
        "Equivalent Ratios",
        "Signed Integer Operations",
        "Signed Fraction Operations",
        "Absolute Value Expression",
        "One-Step Inequality",
        "Mean Absolute Deviation",
        "Interquartile Range",
    ]),
    ("Grade 7", 7, [
        "Basic Algebra",
        "Complementary and Supplementary Angle",
        "Third Angle of Triangle",
        "Fourth Angle of Quadrilateral",
        "Area of Circle",
        "Circumference of Circle",
        "Area of Circle given center and a point on circle",
        "Surface area of a cone",
        "Surface area of a cylinder",
        "Curved surface area of a cylinder",
        "Surface area of a pyramid",
        "Simple Interest",
        "Profit or Loss Percent",
        "Celsius to Fahrenheit",
        "Percentage difference between two numbers",
        "Percentage error",
        "Probability of a certain sum appearing on faces of dice",
        "Solve a Proportion",
        "Multi-Step Inequality",
        "Constant of Proportionality",
    ]),
    ("Grade 8", 8, [
        "Square Root",
        "Cube Root",
        "Product of scientific notations",
        "Pythagorean Theorem",
        "Volume of a cylinder",
        "Volume of a cone",
        "Volume of a sphere",
        "Volume of a hemisphere",
        "Surface area of a sphere",
        "Solve a System of Equations in R^2",
        "Linear Equations",
        "Scientific Notation Operations",
        "Integer Exponent Rules",
        "Evaluate a Function",
        "Slope from Two Points",
        "Linear Function Value",
        "Approximate an Irrational Square Root",
        "Translate a Point",
        "Reflect a Point",
        "Rotate a Point",
        "Dilate a Point",
    ]),
    ("Algebra I", 9, [
        "Simplify Square Root",
        "Power of Powers",
        "Quotient of Powers with Same Base",
        "Quotient of Powers with Same Power",
        "Comparing Surds",
        "Expanding Factored Binomial",
        "Factoring Quadratic",
        "Quadratic Equation",
        "Vertex of a Quadratic in Vertex Form",
        "Intersection of two lines",
        "Equation of Line from Two Points",
        "Equation of line from two points",
        "Compound Interest",
        "Arithmetic Progression Sum",
        "Arithmetic Progression Term",
        "Geometric Progression",
        "Absolute Value Equation",
        "Exponential Growth and Decay",
        "Evaluate an Exponential Function",
        "Domain of a Function",
        "Discriminant and Number of Real Roots",
        "Axis of Symmetry of a Parabola",
        "Sum and Product of the Roots",
        "Solve a Linear Inequality",
    ]),
    ("Geometry", 10, [
        "Distance between 2 points",
        "Midpoint of two points",
        "Trigonometric Values",
        "Arc length of Angle",
        "Area of a Sector",
        "Degrees to Radians",
        "Radians to Degrees",
        "Sum of Angles of Polygon",
        "Angle of a Regular Polygon",
        "Valid Triangle",
        "Volume of a pyramid",
        "Volume of the frustum of a cone",
        "Right Triangle Side with Trigonometry",
        "Right Triangle Side with the Pythagorean Theorem",
        "Equation of a Circle from Center and Radius",
        "Center and Radius from a Circle Equation",
        "Inscribed Angle Theorem",
        "Conditional Probability from a Two-Way Table",
        "Compound Probability of Independent Events",
        "Expected Value of a Discrete Distribution",
    ]),
    ("Algebra II", 11, [
        "Logarithm",
        "Complex Quadratic Equation",
        "Multiplication of 2 complex numbers",
        "Determinant to 2x2 Matrix",
        "Multiply Two Matrices",
        "Multiply Integer to 2x2 Matrix",
        "Invert Matrix",
        "Average Rate of Change over Interval",
        "Factorial",
        "Union, Intersection, Difference of Two Sets",
        "Combinations of Objects",
        "Permutations",
        "Evaluate a Polynomial",
        "Polynomial Division by a Linear Factor",
        "Remainder Theorem",
        "Build a Polynomial from Its Roots",
        "Add and Subtract Complex Numbers",
        "Rational Exponents",
        "Solve a Radical Equation",
        "Solve an Exponential Equation with Logarithms",
        "Evaluate a Logarithm",
        "Inverse of a Linear Function",
        "Z-Score of a Data Value",
        "Empirical Rule (68-95-99.7)",
        "Solve a 2x2 Linear System",
    ]),
    ("Statistical Reasoning", 12, [
        "Mean, Standard Deviation and Variance",
        "Conditional Probability",
        "Binomial distribution",
        "Confidence interval For sample S",
        "Five-Number Summary",
        "Z-Score",
        "Correlation Coefficient",
        "Least-Squares Regression Line",
        "Margin of Error",
        "Standard Error of the Mean",
        "Sample Proportion Confidence Interval",
        "Relative Frequency",
    ]),
    ("Pre-Calculus", 12, [
        "Angle Sum",
        "Angle between 2 vectors",
        "Dot product of 2 vectors",
        "Cross product of 2 vectors",
        "Orthogonal Projection",
        "Euclidian norm or L2 norm of a vector",
        "Complex to polar form",
        "Law of Sines",
        "Law of Cosines",
        "Area of an Oblique Triangle",
        "Inverse Trigonometric Values",
        "Double-Angle Values",
        "Solve a Trigonometric Equation",
        "Polar to Rectangular Coordinates",
        "Rectangular to Polar Coordinates",
        "Finite Geometric Series Sum",
        "Sigma-Notation Arithmetic Sum",
        "Limit of a Rational Sequence",
        "Vector Operations (2D)",
        "Eliminate the Parameter",
    ]),
    ("AP Calculus", 12, [
        "Power Rule Differentiation",
        "Power Rule Integration",
        "Definite Integral of Quadratic Equation",
        "Stationary Points",
        "Trigonometric Differentiation",
        "Limit of a Rational Function",
        "Derivative of a Polynomial",
        "Product Rule at a Point",
        "Quotient Rule at a Point",
        "Chain Rule at a Point",
        "Derivative of Exponential, Log, or Trig Function",
        "Higher-Order Derivative at a Point",
        "Tangent Line to a Polynomial",
        "Critical Points and Extrema",
        "Inflection Point of a Cubic",
        "Definite Integral of a Polynomial",
        "Indefinite Integral of a Polynomial",
        "Definite Integral by u-Substitution",
        "Area Between Curves",
        "Average Value of a Function",
        "Riemann Sum",
    ]),
]


class Command(BaseCommand):
    help = "Seed Course objects and link existing Topics to their courses"

    def handle(self, *args, **options):
        courses_created = 0
        topics_linked = 0
        topics_missing = []

        for course_name, grade_level, topic_names in CURRICULUM:
            course, created = Course.objects.get_or_create(
                course_name=course_name,
                defaults={"grade_level": grade_level},
            )
            if created:
                courses_created += 1

            for name in topic_names:
                try:
                    topic = Topic.objects.get(topic_name=name)
                    topic.course = course
                    topic.save()
                    topics_linked += 1
                except Topic.DoesNotExist:
                    topics_missing.append(name)

        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {courses_created} course(s) created, {topics_linked} topic(s) linked."
            )
        )
        if topics_missing:
            self.stdout.write(
                self.style.WARNING(f"Topics not found: {topics_missing}")
            )
